import type { Metadata } from "next";
import {Ibarra_Real_Nova } from "next/font/google";
import "./globals.css";

const ibarraRealNova = Ibarra_Real_Nova({
  variable: "--font-ibarra-real-nova",
  subsets: ["latin"],
  style: ["normal", "italic"],
  
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ibarraRealNova.className} ${ibarraRealNova.variable}`}>
      <body className="bg-[#FAF7F2]">
        {children}
      </body>
    </html>
  );
}
